version: 2.1

############################################################################

references:
   checkout_job_steps: &checkout_job_steps
      steps:
         - checkout
         - run:
            name: Cloning dependency repositories..
            command: |
               git clone -b develop --single-branch https://github.com/Zimbra/zm-pkg-tool.git ~/zm-pkg-tool
               git clone -b develop --single-branch https://github.com/Zimbra/zm-zcs.git ~/zm-zcs
               git clone -b master --single-branch https://github.com/Zimbra/zimbra-package-stub.git ~/zimbra-package-stub
               git clone -b develop --single-branch https://github.com/Zimbra/zm-mailbox.git ~/zm-mailbox
               mkdir -p ~/.zcs-deps

         - persist_to_workspace:
            root: ..
            paths:
               - zm-openid-consumer-store
               - zm-pkg-tool
               - zm-zcs
               - zimbra-package-stub
               - zm-mailbox
               - .zcs-deps

############################################################################

   build_job_steps: &build_job_steps
      steps:
         - attach_workspace:
            at: ..

         - run:
            name: Compiling required dependencies and creating artifacts
            command: |
              mkdir -p /home/build/.ivy2/cache
              sudo apt-get update && sudo apt-get install ant-contrib -y

              VERSION="${BUILD_RELEASE_NO}_${CIRCLE_BUILD_NUM}"

              MAJOR_VERSION=$(echo "$BUILD_RELEASE_NO" | cut -d'.' -f1)
              MINOR_VERSION=$(echo "$BUILD_RELEASE_NO" | cut -d'.' -f2)
              MICRO_TAG=$(echo "$BUILD_RELEASE_NO" | cut -d'.' -f3 | cut -d'_' -f1)

              echo "VERSION=$VERSION"
              echo "MAJOR=$MAJOR_VERSION MINOR=$MINOR_VERSION MICRO=$MICRO_TAG"

              run_ant() {
                JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && export JAVA_HOME && \
                ant \
                  -Dzimbra.buildinfo.version="$VERSION" \
                  -Dzimbra.buildinfo.majorversion="$MAJOR_VERSION" \
                  -Dzimbra.buildinfo.minorversion="$MINOR_VERSION" \
                  -Dzimbra.buildinfo.microtag="$MICRO_TAG" "$@"
              }

              cd ../zm-mailbox/
              run_ant clean publish-local-all

              cd ../zm-openid-consumer-store
              run_ant clean publish-local

         - persist_to_workspace:
            root: ..
            paths:
               - zm-openid-consumer-store/build
               - .zcs-deps

############################################################################

   publish_job_steps: &publish_job_steps
      steps:
         - attach_workspace:
            at: ..

         - run:
            name: Publishing artifacts to Nexus Artifactory
            command: |
              sudo apt-get update && sudo apt-get install ant-contrib -y

              VERSION="${BUILD_RELEASE_NO}_${CIRCLE_BUILD_NUM}"

              MAJOR_VERSION=$(echo "$BUILD_RELEASE_NO" | cut -d'.' -f1)
              MINOR_VERSION=$(echo "$BUILD_RELEASE_NO" | cut -d'.' -f2)
              MICRO_TAG=$(echo "$BUILD_RELEASE_NO" | cut -d'.' -f3 | cut -d'_' -f1)

              echo "Publishing VERSION=$VERSION"

              run_ant() {
                JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && export JAVA_HOME && \
                ant \
                  -Dzimbra.buildinfo.version="$VERSION" \
                  -Dzimbra.buildinfo.majorversion="$MAJOR_VERSION" \
                  -Dzimbra.buildinfo.minorversion="$MINOR_VERSION" \
                  -Dzimbra.buildinfo.microtag="$MICRO_TAG" "$@"
              }

              cd ../zm-openid-consumer-store
              run_ant publish-remote

############################################################################

jobs:
   checkout:
      working_directory: ~/zm-openid-consumer-store
      shell: /bin/bash -eo pipefail
      docker:
      - image: $DOCKER_REGISTRY/zm-base-os:devcore-ubuntu-22.04
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
      resource_class: small
      <<: *checkout_job_steps

   build:
      working_directory: ~/zm-openid-consumer-store
      shell: /bin/bash -eo pipefail
      docker:
      - image: $DOCKER_REGISTRY/zm-base-os:devcore-ubuntu-22.04
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
      resource_class: medium
      <<: *build_job_steps

   publish:
      working_directory: ~/zm-openid-consumer-store
      shell: /bin/bash -eo pipefail
      circleci_ip_ranges: true
      docker:
      - image: $DOCKER_REGISTRY/zm-base-os:devcore-ubuntu-22.04
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
      resource_class: small
      <<: *publish_job_steps

############################################################################

workflows:
   version: 2
   main:
      jobs:
         - checkout:
            context:
               - docker-dev-registry
         - build:
            context:
               - build-info
               - docker-dev-registry
            requires:
               - checkout
         - publish:
            context:
               - docker-dev-registry
               - build-info
               - nexus-dev-artifactory
            requires:
               - build
            filters:
               branches:
                 only:
                   - develop
